app:
    resource: '@AppBundle/Controller/'
    type: annotation
home:
    path:     /home
    defaults: { _controller: 'TelaPrincipal::home' }
ajax:
    path:     /ajax
    defaults: { _controller: 'Administrador::ajax' }
    