app:
    resource: '@AppBundle/Controller/'
    type: annotation
home:
    path:     /home
    defaults: { _controller: 'TelaPrincipal::home' }
administradores:
    path:     /administradores
    defaults: { _controller: 'Administrador::administradores' }       