AppBundle\Entity\TbActivity:
    type: entity
    table: tb_activity
    indexes:
        fk_tb_atividade_tb_portfolio_idx:
            columns:
                - id_portfolio
    uniqueConstraints:
        tb_activity_id_activity_idx:
            columns:
                - id_activity
    id:
        idActivity:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_activity
            generator:
                strategy: SEQUENCE
    fields:
        nuOrder:
            type: smallint
            nullable: true
            options:
                unsigned: false
            column: nu_order
        dsTitle:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: ds_title
        dsDescription:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: ds_description
    manyToOne:
        idPortfolio:
            targetEntity: TbPortfolio
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_portfolio:
                    referencedColumnName: id_portfolio
            orphanRemoval: false
    lifecycleCallbacks: {  }
