AppBundle\Entity\TbAttachActivity:
    type: entity
    table: tb_attach_activity
    indexes:
        IDX_EAB69C9DDCD5596C:
            columns:
                - id_attachment
        IDX_EAB69C9D54FB8C02:
            columns:
                - id_activity_student
    id:
        idAttachActivity:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_attach_activity
            generator:
                strategy: SEQUENCE
    manyToOne:
        idAttachment:
            targetEntity: TbAttachment
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_attachment:
                    referencedColumnName: id_attachment
            orphanRemoval: false
        idActivityStudent:
            targetEntity: TbActivityStudent
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_activity_student:
                    referencedColumnName: id_activity_student
            orphanRemoval: false
    lifecycleCallbacks: {  }
