AppBundle\Entity\TbReference:
    type: entity
    table: tb_reference
    indexes:
        fk_tb_reference_tb_activity_student1_idx:
            columns:
                - id_activity_student
    uniqueConstraints:
        tb_reference_id_reference_idx:
            columns:
                - id_reference
    id:
        idReference:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_reference
            generator:
                strategy: SEQUENCE
    fields:
        dsUrl:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
            column: ds_url
        idReferenceSrv:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: id_reference_srv
    manyToOne:
        idActivityStudent:
            targetEntity: TbActivityStudent
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_activity_student:
                    referencedColumnName: id_activity_student
            orphanRemoval: false
    lifecycleCallbacks: {  }
