AppBundle\Entity\TbSync:
    type: entity
    table: tb_sync
    indexes:
        IDX_775BF76B54FB8C02:
            columns:
                - id_activity_student
        IDX_775BF76B9B986D25:
            columns:
                - id_author
        IDX_775BF76B26D4F35D:
            columns:
                - id_destination
    id:
        idSync:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_sync
            generator:
                strategy: SEQUENCE
    fields:
        nmTable:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: nm_table
        coIdTable:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: co_id_table
        dtSync:
            type: datetime
            nullable: true
            column: dt_sync
    manyToOne:
        idActivityStudent:
            targetEntity: TbActivityStudent
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_activity_student:
                    referencedColumnName: id_activity_student
            orphanRemoval: false
        idAuthor:
            targetEntity: TbUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_author:
                    referencedColumnName: id_user
            orphanRemoval: false
        idDestination:
            targetEntity: TbUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_destination:
                    referencedColumnName: id_user
            orphanRemoval: false
    lifecycleCallbacks: {  }
