AppBundle\Entity\TbVersionActivity:
    type: entity
    table: tb_version_activity
    indexes:
        IDX_911173354FB8C02:
            columns:
                - id_activity_student
    id:
        idVersionActivity:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_version_activity
            generator:
                strategy: SEQUENCE
    fields:
        txActivity:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
            column: tx_activity
        dtLastAccess:
            type: datetime
            nullable: true
            column: dt_last_access
        dtSubmission:
            type: datetime
            nullable: true
            column: dt_submission
        dtVerification:
            type: datetime
            nullable: true
            column: dt_verification
        idVersionActivitySrv:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: id_version_activity_srv
    manyToOne:
        idActivityStudent:
            targetEntity: TbActivityStudent
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_activity_student:
                    referencedColumnName: id_activity_student
            orphanRemoval: false
    lifecycleCallbacks: {  }
